---
name: Check reviews
description: Check reviews must include setting members
inputs:
  token:
    description: >
      GitHub Access Token. The user associated with this token will show up
      as the "creator" of the status check, and must have access to read
      pull request data, create status checks (`repo:status`), and to read
      your organization's teams (`read:org`).
    required: true
  teams:
    description: must include teams
    required: true

runs:
  using: node16
  main: dist/index.js